-- Run against a fresh disposable PostgreSQL 17 database after migrations 001–026.
do $guard$ begin if current_setting('app.disposable_test', true) is distinct from 'true' then raise exception 'disposable_database_guard_required'; end if; end $guard$;
create function pg_temp.assert_true(p_condition boolean, p_case text) returns void language plpgsql as $assert$ begin if not coalesce(p_condition, false) then raise exception using errcode = 'P0001', message = p_case; end if; end $assert$;

insert into public.profiles (id, email, credits) values ('user_026_a', 'a@example.invalid', 0), ('user_026_b', 'b@example.invalid', 0);
insert into public.product_types (name) values ('Snapshot coats'), ('Snapshot shirts');
insert into public.product_subtypes (product_type_id, name) select id, name || ' subtype' from public.product_types where name in ('Snapshot coats', 'Snapshot shirts');
insert into public.products (id, title, slug, price, category, product_type_id, product_subtype_id)
select case types.name when 'Snapshot coats' then '26000000-0000-0000-0000-000000000001'::uuid else '26000000-0000-0000-0000-000000000002'::uuid end, types.name, lower(replace(types.name, ' ', '-')), case types.name when 'Snapshot coats' then 100 else 100.01 end, 'fixture', types.id, subtypes.id from public.product_types types join public.product_subtypes subtypes on subtypes.product_type_id = types.id where types.name in ('Snapshot coats', 'Snapshot shirts');
insert into public.products (id, title, slug, price, category, product_type_id, product_subtype_id) select '26000000-0000-0000-0000-000000000003'::uuid, 'Snapshot coat two', 'snapshot-coat-two', 100, 'fixture', types.id, subtypes.id from public.product_types types join public.product_subtypes subtypes on subtypes.product_type_id = types.id where types.name = 'Snapshot coats';
select id as coat_type_id from public.product_types where name = 'Snapshot coats' \gset
select id as shirt_type_id from public.product_types where name = 'Snapshot shirts' \gset
select public.create_promotion('snapshot_admin', 1000, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', jsonb_build_array(jsonb_build_object('product_type_id', :'coat_type_id'::uuid))) as coat_promotion_id \gset
select public.create_promotion('snapshot_admin', 2000, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', jsonb_build_array(jsonb_build_object('product_type_id', :'shirt_type_id'::uuid))) as shirt_promotion_id \gset
select public.create_coupon('snapshot_admin', 'SNAP50', 1, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', null, 999999) as coupon_id \gset

do $stale$ begin begin perform public.create_product_checkout('user_026_a', '{"email":"a@example.invalid","fullName":"A User"}'::jsonb, array['26000000-0000-0000-0000-000000000099'::uuid], 20, 'promotions', null, null, null); raise exception 'stale_id_accepted'; exception when others then if sqlerrm = 'stale_id_accepted' then raise; end if; end; end $stale$;
create temp table default_order as select * from public.create_product_checkout('user_026_a', '{"email":"a@example.invalid","fullName":"A User"}'::jsonb, array['26000000-0000-0000-0000-000000000001'::uuid], 20, 'promotions', null, null, null);
select pg_temp.assert_true((select pricing_source = 'promotions' and merchandise_original_cents = 10000 and merchandise_discount_cents = 1000 and merchandise_final_cents = 9000 and shipping_cents = 2000 and total_cents = payment_amount_cents from public.orders where id = (select order_id from default_order)) and (select count(*) = 0 from public.coupon_checkout_reservations) and (select used_count = 0 from public.coupon_definitions where id = :'coupon_id'::uuid), 'default_source_must_select_promotions_without_coupon_reservation');
do $status_authority$ begin
  begin update public.orders set status = 'paid' where id = (select order_id from default_order); raise exception 'direct_order_status_update_accepted'; exception when others then if sqlerrm <> 'order_status_transition_not_authorized' then raise; end if; end;
  begin update public.orders set status = status where id = (select order_id from default_order); raise exception 'direct_order_status_noop_update_accepted'; exception when others then if sqlerrm <> 'order_status_transition_not_authorized' then raise; end if; end;
  begin update public.orders set merchandise_final_cents = 1 where id = (select order_id from default_order); raise exception 'discount_snapshot_mutable'; exception when others then if sqlerrm = 'discount_snapshot_mutable' then raise; end if; end;
end $status_authority$;
create temp table settled_default_order as select * from public.settle_product_payment('mercadopago', 'pay-026-default', 'approved', (select reference from default_order), 110, 'ARS', null);
select pg_temp.assert_true((select newly_applied and result = 'applied' from settled_default_order) and (select status = 'paid' from public.orders where id = (select order_id from default_order)), 'authoritative_settlement_must_succeed');
create temp table shipped_default_order as select public.ship_product_order((select order_id from default_order), 'RR026DEFAULT') as first_transition;
select pg_temp.assert_true((select first_transition from shipped_default_order) and public.ship_product_order((select order_id from default_order), 'RR026DEFAULT') and (select status = 'shipped' and tracking_number = 'RR026DEFAULT' from public.orders where id = (select order_id from default_order)), 'authoritative_shipping_must_succeed_idempotently');

create temp table coupon_order as select * from public.create_product_checkout('user_026_b', '{"email":"b@example.invalid","fullName":"B User"}'::jsonb, array['26000000-0000-0000-0000-000000000002'::uuid, '26000000-0000-0000-0000-000000000003'::uuid], 20, 'coupon', 'SNAP50', 'v1', repeat('d', 64));
select pg_temp.assert_true((select pricing_source = 'coupon' and coupon_id = :'coupon_id'::uuid and coupon_discount_cents = 10000 and merchandise_original_cents = 20001 and merchandise_final_cents = 10001 and shipping_cents = 2000 and total_cents = 12001 and payment_amount_cents = 12001 and identity_key_version = 'v1' and coupon_reservation_state = 'reserved' from public.orders where id = (select order_id from coupon_order)) and (select sum(discount_cents) = 10000 and sum(final_cents) = 10001 and max(discount_cents) = 5000 and min(discount_cents) = 5000 and bool_and(pricing_source = 'coupon' and coupon_id = :'coupon_id'::uuid and fixed_discount_cents = 999999) from public.order_items where order_id = (select order_id from coupon_order)) and (select used_count = 1 from public.coupon_definitions where id = :'coupon_id'::uuid) and (select count(*) = 1 from public.coupon_checkout_reservations where order_id = (select order_id from coupon_order) and reservation_state = 'reserved') and (select count(*) = 2 from public.inventory_reservations where order_id = (select order_id from coupon_order) and status = 'active'), 'coupon_must_cap_and_allocate_largest_remainder_exactly');
do $coupon_state_authority$
declare v_state text;
begin
  foreach v_state in array array['reserved', 'consumed', 'released', 'expired'] loop
    begin
      update public.orders set coupon_reservation_state = v_state where id = (select order_id from coupon_order);
      raise exception 'direct_coupon_reservation_state_update_accepted:%', v_state;
    exception when others then
      if sqlerrm like 'direct_coupon_reservation_state_update_accepted:%' or sqlerrm <> 'coupon_reservation_state_transition_not_authorized' then raise; end if;
    end;
  end loop;
end $coupon_state_authority$;
select pg_temp.assert_true((select is_active and used_count = 1 from public.coupon_definitions where id = :'coupon_id'::uuid) and (select count(*) = 1 from public.coupon_checkout_reservations where order_id = (select order_id from coupon_order) and coupon_id = :'coupon_id'::uuid and key_version = 'v1' and fingerprint = repeat('d', 64) and reservation_state = 'reserved') and (select count(*) = 2 from public.products where id in ('26000000-0000-0000-0000-000000000002'::uuid, '26000000-0000-0000-0000-000000000003'::uuid) and status = 'reserved') and not exists (select 1 from public.coupon_used_count_authorizations where order_id = (select order_id from coupon_order)), 'active_coupon_checkout_must_increment_reserve_and_consume_authorization_atomically');
do $coupon_counter_authority$ begin
  insert into public.coupon_used_count_authorizations (order_id, coupon_id, expected_used_count, next_used_count) select order_id, (select id from public.coupon_definitions where code = 'SNAP50'), 1, 2 from coupon_order;
  begin update public.coupon_definitions set used_count = used_count where code = 'SNAP50'; raise exception 'active_coupon_counter_noop_accepted'; exception when others then if sqlerrm <> 'coupon_used_count_not_authorized' then raise; end if; end; if not exists (select 1 from public.coupon_used_count_authorizations where order_id = (select order_id from coupon_order)) then raise exception 'coupon_used_count_noop_consumed_authorization'; end if; delete from public.coupon_used_count_authorizations where order_id = (select order_id from coupon_order);
  begin update public.coupon_definitions set used_count = used_count + 1 where code = 'SNAP50'; raise exception 'active_coupon_counter_increment_accepted'; exception when others then if sqlerrm <> 'coupon_used_count_not_authorized' then raise; end if; end;
  begin update public.coupon_definitions set used_count = used_count - 1 where code = 'SNAP50'; raise exception 'active_coupon_counter_decrement_accepted'; exception when others then if sqlerrm <> 'coupon_used_count_not_authorized' then raise; end if; end;
  insert into public.coupon_used_count_authorizations (order_id, coupon_id, expected_used_count, next_used_count) select order_id, (select id from public.coupon_definitions where code = 'SNAP50'), 1, 2 from default_order;
  begin update public.coupon_definitions set used_count = used_count + 1 where code = 'SNAP50'; raise exception 'cross_order_coupon_counter_authorization_accepted'; exception when others then if sqlerrm <> 'coupon_used_count_not_authorized' then raise; end if; end;
  delete from public.coupon_used_count_authorizations where order_id = (select order_id from default_order);
end $coupon_counter_authority$;

select public.create_coupon('snapshot_admin', 'GUARD26', 2, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', 1000, null);
do $coupon_guard$ begin
  begin update public.coupon_definitions set used_count = used_count + 1 where code = 'GUARD26'; raise exception 'active_coupon_counter_increment_accepted'; exception when others then if sqlerrm <> 'coupon_used_count_not_authorized' then raise; end if; end;
  begin update public.coupon_definitions set capacity = 3 where code = 'GUARD26'; raise exception 'coupon_terms_mutable'; exception when others then if sqlerrm <> 'coupon_terms_immutable' then raise; end if; end;
  begin update public.coupon_definitions set is_active = false, deactivated_at = statement_timestamp() where code = 'GUARD26'; raise exception 'coupon_deactivation_without_reason_accepted'; exception when others then if sqlerrm <> 'coupon_deactivation_reason_required' then raise; end if; end;
   update public.coupon_definitions set is_active = false, deactivated_at = statement_timestamp(), deactivation_reason = 'campaign ended' where code = 'GUARD26';
   begin update public.coupon_definitions set deactivation_reason = 'rewritten reason' where code = 'GUARD26'; raise exception 'coupon_deactivation_reason_mutable'; exception when others then if sqlerrm <> 'coupon_deactivation_immutable' then raise; end if; end;
   begin update public.coupon_definitions set is_active = true where code = 'GUARD26'; raise exception 'coupon_reactivation_accepted'; exception when others then if sqlerrm <> 'coupon_reactivation_forbidden' then raise; end if; end;
end $coupon_guard$;
do $authorization_acl$ declare v_role text; v_table text; v_statement text; begin foreach v_role in array array['anon', 'authenticated'] loop execute format('set local role %I', v_role); foreach v_table in array array['product_payment_reversal_evidence', 'coupon_reservation_release_evidence', 'order_status_transition_authorizations', 'coupon_used_count_authorizations'] loop foreach v_statement in array array[format('select 1 from public.%I limit 1', v_table), format('insert into public.%I default values', v_table)] loop begin execute v_statement; raise exception 'authorization_table_access_accepted:%:%', v_role, v_table; exception when insufficient_privilege then null; end; end loop; end loop; end loop; set local role none; end $authorization_acl$;
select pg_temp.assert_true(not has_function_privilege('anon', 'public.settle_product_payment(text,text,text,text,numeric,text)', 'execute') and not has_function_privilege('authenticated', 'public.settle_product_payment(text,text,text,text,numeric,text)', 'execute') and not has_function_privilege('service_role', 'public.settle_product_payment(text,text,text,text,numeric,text)', 'execute') and has_function_privilege('postgres', 'public.settle_product_payment(text,text,text,text,numeric,text)', 'execute') and has_function_privilege('service_role', 'public.settle_product_payment(text,text,text,text,numeric,text,numeric)', 'execute') and has_function_privilege('postgres', 'public.settle_product_payment(text,text,text,text,numeric,text,numeric)', 'execute'), 'legacy_settlement_must_not_be_application_executable');
insert into public.profiles (id, email, credits) values ('user_026_tie', 'tie@example.invalid', 0);
insert into public.products (id, title, slug, price, category, product_type_id, product_subtype_id) select ids.id, ids.slug, ids.slug, 1, 'fixture', types.id, subtypes.id from (values ('26000000-0000-0000-0000-000000000004'::uuid, 'snapshot-tie-a'), ('26000000-0000-0000-0000-000000000005'::uuid, 'snapshot-tie-b')) ids(id, slug) cross join public.product_types types join public.product_subtypes subtypes on subtypes.product_type_id = types.id where types.name = 'Snapshot coats';
select public.create_coupon('snapshot_admin', 'SNAP1', 1, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', null, 1) as tie_coupon_id \gset
create temp table tie_order as select * from public.create_product_checkout('user_026_tie', '{"email":"tie@example.invalid","fullName":"Tie User"}'::jsonb, array['26000000-0000-0000-0000-000000000005'::uuid, '26000000-0000-0000-0000-000000000004'::uuid], 0, 'coupon', 'SNAP1', 'v1', repeat('e', 64));
select pg_temp.assert_true((select discount_cents = 1 from public.order_items where order_id = (select order_id from tie_order) and product_id = '26000000-0000-0000-0000-000000000004'::uuid) and (select discount_cents = 0 from public.order_items where order_id = (select order_id from tie_order) and product_id = '26000000-0000-0000-0000-000000000005'::uuid), 'largest_remainder_ties_must_use_product_uuid_order');

do $immutable$ begin begin update public.order_items set discount_cents = 0 where order_id = (select order_id from coupon_order); raise exception 'discount_snapshot_mutable'; exception when others then if sqlerrm = 'discount_snapshot_mutable' then raise; end if; end; end $immutable$;
create extension if not exists dblink;
select dblink_connect('checkout_coupon_lock', current_setting('app.disposable_dblink_connection'));
select dblink_exec('checkout_coupon_lock', 'begin');
select dblink_exec('checkout_coupon_lock', 'do $lock$ begin perform pg_advisory_xact_lock(hashtextextended(''coupon-code:SNAP50'', 0)); end $lock$');
select pg_temp.assert_true(not pg_try_advisory_xact_lock(hashtextextended('coupon-code:SNAP50', 0)) and pg_get_functiondef('public.create_product_checkout(text,jsonb,uuid[],numeric,text,text,text,text)'::regprocedure) like '%for update%' and pg_get_functiondef('public.create_product_checkout(text,jsonb,uuid[],numeric,text,text,text,text)'::regprocedure) like '%coupon-identity:%', 'checkout_must_lock_coupon_identity_and_products');
select dblink_exec('checkout_coupon_lock', 'rollback'); select dblink_disconnect('checkout_coupon_lock');
select pg_temp.assert_true((select result = 'invalid_payment' from public.settle_product_payment('mercadopago', 'pay-026-subcent-a', 'refunded', (select reference from coupon_order), 120.006, 'ARS', 120.01)) and (select result = 'invalid_payment' from public.settle_product_payment('mercadopago', 'pay-026-subcent-b', 'refunded', (select reference from coupon_order), 120.01, 'ARS', 120.004)) and (select result = 'invalid_payment' from public.settle_product_payment('forged', 'pay-026-provider', 'refunded', (select reference from coupon_order), 120.01, 'ARS', 120.01)) and not exists (select 1 from public.product_payment_reversal_evidence where payment_id = 'pay-026-provider'), 'provider_and_reversal_amounts_must_be_exact_cents');
create temp table settled_coupon_order as select * from public.settle_product_payment('mercadopago', 'pay-026-coupon', 'approved', (select reference from coupon_order), 120.01, 'ARS', null);
select pg_temp.assert_true((select newly_applied and result = 'applied' from settled_coupon_order) and (select status = 'paid' and coupon_reservation_state = 'consumed' from public.orders where id = (select order_id from coupon_order)) and (select reservation_state = 'consumed' from public.coupon_checkout_reservations where order_id = (select order_id from coupon_order)) and (select count(*) = 1 from public.coupon_identity_uses where coupon_id = :'coupon_id'::uuid and key_version = 'v1' and fingerprint = repeat('d', 64)) and (select count(*) = 2 from public.inventory_reservations where order_id = (select order_id from coupon_order) and status = 'sold'), 'approval_must_consume_coupon_and_inventory_once');
create temp table replayed_coupon_order as select * from public.settle_product_payment('mercadopago', 'pay-026-coupon', 'approved', (select reference from coupon_order), 120.01, 'ARS', null);
select pg_temp.assert_true(not (select newly_applied from replayed_coupon_order) and (select count(*) = 1 from public.coupon_identity_uses where coupon_id = :'coupon_id'::uuid and key_version = 'v1' and fingerprint = repeat('d', 64)), 'approval_replay_must_not_consume_twice');
create temp table refunded_coupon_order as select * from public.settle_product_payment('mercadopago', 'pay-026-coupon', 'refunded', (select reference from coupon_order), 120.01, 'ARS', 120.01);
select pg_temp.assert_true((select result = 'manual_review_required' from refunded_coupon_order) and (select count(*) = 1 from public.product_payment_reversal_evidence where order_id = (select order_id from coupon_order) and event_class = 'refunded' and reversal_total_cents = 12001) and (select used_count = 1 from public.coupon_definitions where id = :'coupon_id'::uuid) and (select reservation_state = 'consumed' from public.coupon_checkout_reservations where order_id = (select order_id from coupon_order)), 'refund_must_record_evidence_without_restoring_coupon');
update public.coupon_definitions set is_active = false, deactivated_at = statement_timestamp(), deactivation_reason = 'campaign ended' where id = :'tie_coupon_id'::uuid;
do $inactive_counter$ begin begin update public.coupon_definitions set used_count = used_count - 1 where code = 'SNAP1'; raise exception 'inactive_coupon_counter_decrement_accepted'; exception when others then if sqlerrm <> 'coupon_used_count_not_authorized' then raise; end if; end; begin update public.coupon_definitions set used_count = used_count + 1 where code = 'SNAP1'; raise exception 'inactive_coupon_counter_increment_accepted'; exception when others then if sqlerrm <> 'coupon_used_count_not_authorized' then raise; end if; end; end $inactive_counter$;
create temp table rejected_tie_order as select * from public.settle_product_payment('mercadopago', 'pay-026-release', 'rejected', (select reference from tie_order), 1.99, 'ARS', null);
select pg_temp.assert_true((select result = 'cancelled' from rejected_tie_order), 'rejection_must_cancel_order');
select pg_temp.assert_true((select coupon_reservation_state = 'released' from public.orders where id = (select order_id from tie_order)) and (select count(*) = 2 from public.inventory_reservations where order_id = (select order_id from tie_order) and status = 'released') and (select count(*) = 2 from public.products where id in ('26000000-0000-0000-0000-000000000004'::uuid, '26000000-0000-0000-0000-000000000005'::uuid) and status = 'available'), 'rejection_must_release_inventory_atomically');
select pg_temp.assert_true((select count(*) = 1 from public.coupon_reservation_release_evidence where order_id = (select order_id from tie_order)), 'rejection_must_record_coupon_release');
select pg_temp.assert_true((select used_count = 0 and not is_active from public.coupon_definitions where id = :'tie_coupon_id'::uuid) and not exists (select 1 from public.coupon_checkout_reservations where order_id = (select order_id from tie_order)) and not exists (select 1 from public.coupon_identity_uses where coupon_id = :'tie_coupon_id'::uuid) and not exists (select 1 from public.coupon_used_count_authorizations where order_id = (select order_id from tie_order)) and not exists (select 1 from public.order_status_transition_authorizations where order_id = (select order_id from tie_order)) and (select result = 'duplicate_event' from public.settle_product_payment('mercadopago', 'pay-026-release', 'rejected', (select reference from tie_order), 1.99, 'ARS', null)), 'inactive_rejection_must_release_capacity_identity_and_authorization_exactly_once');
select public.create_coupon('snapshot_admin', 'EXPIRE1', 1, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', 1000, null) as expire_coupon_id \gset
create temp table expired_coupon_order as select * from public.create_product_checkout('user_026_tie', '{"email":"tie@example.invalid","fullName":"Tie User"}'::jsonb, array['26000000-0000-0000-0000-000000000004'::uuid], 0, 'coupon', 'EXPIRE1', 'v1', repeat('f', 64));
update public.coupon_definitions set is_active = false, deactivated_at = statement_timestamp(), deactivation_reason = 'expired campaign' where id = :'expire_coupon_id'::uuid;
select public.expire_product_reservations(statement_timestamp() + interval '1 hour', 10);
select pg_temp.assert_true((select status = 'cancelled' and coupon_reservation_state = 'released' from public.orders where id = (select order_id from expired_coupon_order)) and (select used_count = 0 from public.coupon_definitions where id = :'expire_coupon_id'::uuid) and (select count(*) = 1 from public.coupon_reservation_release_evidence where order_id = (select order_id from expired_coupon_order)) and (select status = 'available' from public.products where id = '26000000-0000-0000-0000-000000000004'::uuid) and not exists (select 1 from public.coupon_identity_uses where coupon_id = :'expire_coupon_id'::uuid) and not exists (select 1 from public.coupon_used_count_authorizations where order_id = (select order_id from expired_coupon_order)), 'inactive_expiry_must_release_coupon_capacity_identity_inventory_and_authorization');
select public.create_coupon('snapshot_admin', 'CANCEL1', 1, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', 1000, null) as cancel_coupon_id \gset
create temp table cancelled_coupon_order as select * from public.create_product_checkout('user_026_tie', '{"email":"tie@example.invalid","fullName":"Tie User"}'::jsonb, array['26000000-0000-0000-0000-000000000005'::uuid], 0, 'coupon', 'CANCEL1', 'v1', repeat('a', 64));
update public.coupon_definitions set is_active = false, deactivated_at = statement_timestamp(), deactivation_reason = 'cancelled campaign' where id = :'cancel_coupon_id'::uuid;
create temp table cancelled_coupon_result as select * from public.settle_product_payment('mercadopago', 'pay-026-cancelled', 'cancelled', (select reference from cancelled_coupon_order), .9, 'ARS', null);
select pg_temp.assert_true((select result = 'cancelled' from cancelled_coupon_result) and (select result = 'duplicate_event' from public.settle_product_payment('mercadopago', 'pay-026-cancelled', 'cancelled', (select reference from cancelled_coupon_order), .9, 'ARS', null)) and (select used_count = 0 and not is_active from public.coupon_definitions where id = :'cancel_coupon_id'::uuid) and (select status = 'available' from public.products where id = '26000000-0000-0000-0000-000000000005'::uuid) and not exists (select 1 from public.coupon_checkout_reservations where order_id = (select order_id from cancelled_coupon_order)) and not exists (select 1 from public.coupon_identity_uses where coupon_id = :'cancel_coupon_id'::uuid) and not exists (select 1 from public.coupon_used_count_authorizations where order_id = (select order_id from cancelled_coupon_order)) and not exists (select 1 from public.order_status_transition_authorizations where order_id = (select order_id from cancelled_coupon_order)), 'inactive_cancellation_must_release_capacity_identity_and_authorization_exactly_once');
select '026_discount_settlement_proof_passed' as result;
