-- Run against a fresh disposable PostgreSQL 17 database after migrations 001–026.
do $guard$ begin if current_setting('app.disposable_test', true) is distinct from 'true' then raise exception 'disposable_database_guard_required'; end if; end $guard$;
create function pg_temp.assert_true(p_condition boolean, p_case text) returns void language plpgsql as $assert$ begin if not coalesce(p_condition, false) then raise exception using errcode = 'P0001', message = p_case; end if; end $assert$;

insert into public.profiles (id, email, credits) values ('user_026_a', 'a@example.invalid', 0), ('user_026_b', 'b@example.invalid', 0);
insert into public.product_types (name) values ('Snapshot coats'), ('Snapshot shirts');
insert into public.product_subtypes (product_type_id, name) select id, name || ' subtype' from public.product_types where name in ('Snapshot coats', 'Snapshot shirts');
insert into public.products (id, title, slug, price, category, product_type_id, product_subtype_id)
select case types.name when 'Snapshot coats' then '26000000-0000-0000-0000-000000000001'::uuid else '26000000-0000-0000-0000-000000000002'::uuid end, types.name, lower(replace(types.name, ' ', '-')), case types.name when 'Snapshot coats' then 100 else 100.01 end, 'fixture', types.id, subtypes.id from public.product_types types join public.product_subtypes subtypes on subtypes.product_type_id = types.id where types.name in ('Snapshot coats', 'Snapshot shirts');
insert into public.products (id, title, slug, price, category, product_type_id, product_subtype_id) select '26000000-0000-0000-0000-000000000003'::uuid, 'Snapshot coat two', 'snapshot-coat-two', 100, 'fixture', types.id, subtypes.id from public.product_types types join public.product_subtypes subtypes on subtypes.product_type_id = types.id where types.name = 'Snapshot coats';
select id as coat_type_id from public.product_types where name = 'Snapshot coats' \gset
select id as shirt_type_id from public.product_types where name = 'Snapshot shirts' \gset
select public.create_promotion('snapshot_admin', 1000, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', jsonb_build_array(jsonb_build_object('product_type_id', :'coat_type_id'::uuid))) as coat_promotion_id \gset
select public.create_promotion('snapshot_admin', 2000, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', jsonb_build_array(jsonb_build_object('product_type_id', :'shirt_type_id'::uuid))) as shirt_promotion_id \gset
select public.create_coupon('snapshot_admin', 'SNAP50', 1, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', null, 999999) as coupon_id \gset

do $stale$ begin begin perform public.create_product_checkout('user_026_a', '{"email":"a@example.invalid","fullName":"A User"}'::jsonb, array['26000000-0000-0000-0000-000000000099'::uuid], 20, 'promotions', null, null, null); raise exception 'stale_id_accepted'; exception when others then if sqlerrm = 'stale_id_accepted' then raise; end if; end; end $stale$;
create temp table default_order as select * from public.create_product_checkout('user_026_a', '{"email":"a@example.invalid","fullName":"A User"}'::jsonb, array['26000000-0000-0000-0000-000000000001'::uuid], 20, 'promotions', null, null, null);
select pg_temp.assert_true((select pricing_source = 'promotions' and merchandise_original_cents = 10000 and merchandise_discount_cents = 1000 and merchandise_final_cents = 9000 and shipping_cents = 2000 and total_cents = payment_amount_cents from public.orders where id = (select order_id from default_order)) and (select count(*) = 0 from public.coupon_checkout_reservations) and (select used_count = 0 from public.coupon_definitions where id = :'coupon_id'::uuid), 'default_source_must_select_promotions_without_coupon_reservation');

create temp table coupon_order as select * from public.create_product_checkout('user_026_b', '{"email":"b@example.invalid","fullName":"B User"}'::jsonb, array['26000000-0000-0000-0000-000000000002'::uuid, '26000000-0000-0000-0000-000000000003'::uuid], 20, 'coupon', 'SNAP50', 'v1', repeat('d', 64));
select pg_temp.assert_true((select pricing_source = 'coupon' and coupon_id = :'coupon_id'::uuid and coupon_discount_cents = 10000 and merchandise_original_cents = 20001 and merchandise_final_cents = 10001 and shipping_cents = 2000 and total_cents = 12001 and payment_amount_cents = 12001 and identity_key_version = 'v1' and coupon_reservation_state = 'reserved' from public.orders where id = (select order_id from coupon_order)) and (select sum(discount_cents) = 10000 and sum(final_cents) = 10001 and max(discount_cents) = 5000 and min(discount_cents) = 5000 and bool_and(pricing_source = 'coupon' and coupon_id = :'coupon_id'::uuid and fixed_discount_cents = 999999) from public.order_items where order_id = (select order_id from coupon_order)) and (select used_count = 1 from public.coupon_definitions where id = :'coupon_id'::uuid) and (select count(*) = 1 from public.coupon_checkout_reservations where order_id = (select order_id from coupon_order) and reservation_state = 'reserved') and (select count(*) = 2 from public.inventory_reservations where order_id = (select order_id from coupon_order) and status = 'active'), 'coupon_must_cap_and_allocate_largest_remainder_exactly');
select pg_temp.assert_true((select is_active and used_count = 1 from public.coupon_definitions where id = :'coupon_id'::uuid) and (select count(*) = 1 from public.coupon_checkout_reservations where order_id = (select order_id from coupon_order) and coupon_id = :'coupon_id'::uuid and key_version = 'v1' and fingerprint = repeat('d', 64) and reservation_state = 'reserved') and (select count(*) = 2 from public.products where id in ('26000000-0000-0000-0000-000000000002'::uuid, '26000000-0000-0000-0000-000000000003'::uuid) and status = 'reserved'), 'active_coupon_checkout_must_increment_and_reserve_atomically');

select public.create_coupon('snapshot_admin', 'GUARD26', 2, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', 1000, null);
do $coupon_guard$ begin
  update public.coupon_definitions set used_count = used_count + 1 where code = 'GUARD26';
  begin update public.coupon_definitions set capacity = 3 where code = 'GUARD26'; raise exception 'coupon_terms_mutable'; exception when others then if sqlerrm <> 'coupon_terms_immutable' then raise; end if; end;
  begin update public.coupon_definitions set is_active = false, deactivated_at = statement_timestamp() where code = 'GUARD26'; raise exception 'coupon_deactivation_without_reason_accepted'; exception when others then if sqlerrm <> 'coupon_deactivation_reason_required' then raise; end if; end;
   update public.coupon_definitions set is_active = false, deactivated_at = statement_timestamp(), deactivation_reason = 'campaign ended' where code = 'GUARD26';
   begin update public.coupon_definitions set deactivation_reason = 'rewritten reason' where code = 'GUARD26'; raise exception 'coupon_deactivation_reason_mutable'; exception when others then if sqlerrm <> 'coupon_deactivation_immutable' then raise; end if; end;
   begin update public.coupon_definitions set is_active = true where code = 'GUARD26'; raise exception 'coupon_reactivation_accepted'; exception when others then if sqlerrm <> 'coupon_reactivation_forbidden' then raise; end if; end;
end $coupon_guard$;
insert into public.profiles (id, email, credits) values ('user_026_tie', 'tie@example.invalid', 0);
insert into public.products (id, title, slug, price, category, product_type_id, product_subtype_id) select ids.id, ids.slug, ids.slug, 1, 'fixture', types.id, subtypes.id from (values ('26000000-0000-0000-0000-000000000004'::uuid, 'snapshot-tie-a'), ('26000000-0000-0000-0000-000000000005'::uuid, 'snapshot-tie-b')) ids(id, slug) cross join public.product_types types join public.product_subtypes subtypes on subtypes.product_type_id = types.id where types.name = 'Snapshot coats';
select public.create_coupon('snapshot_admin', 'SNAP1', 1, statement_timestamp() - interval '1 minute', statement_timestamp() + interval '1 hour', null, 1) as tie_coupon_id \gset
create temp table tie_order as select * from public.create_product_checkout('user_026_tie', '{"email":"tie@example.invalid","fullName":"Tie User"}'::jsonb, array['26000000-0000-0000-0000-000000000005'::uuid, '26000000-0000-0000-0000-000000000004'::uuid], 0, 'coupon', 'SNAP1', 'v1', repeat('e', 64));
select pg_temp.assert_true((select discount_cents = 1 from public.order_items where order_id = (select order_id from tie_order) and product_id = '26000000-0000-0000-0000-000000000004'::uuid) and (select discount_cents = 0 from public.order_items where order_id = (select order_id from tie_order) and product_id = '26000000-0000-0000-0000-000000000005'::uuid), 'largest_remainder_ties_must_use_product_uuid_order');

do $immutable$ begin begin update public.order_items set discount_cents = 0 where order_id = (select order_id from coupon_order); raise exception 'discount_snapshot_mutable'; exception when others then if sqlerrm = 'discount_snapshot_mutable' then raise; end if; end; end $immutable$;
create extension if not exists dblink;
select dblink_connect('checkout_coupon_lock', current_setting('app.disposable_dblink_connection'));
select dblink_exec('checkout_coupon_lock', 'begin');
select dblink_exec('checkout_coupon_lock', 'do $lock$ begin perform pg_advisory_xact_lock(hashtextextended(''coupon-code:SNAP50'', 0)); end $lock$');
select pg_temp.assert_true(not pg_try_advisory_xact_lock(hashtextextended('coupon-code:SNAP50', 0)) and pg_get_functiondef('public.create_product_checkout(text,jsonb,uuid[],numeric,text,text,text,text)'::regprocedure) like '%for update%' and pg_get_functiondef('public.create_product_checkout(text,jsonb,uuid[],numeric,text,text,text,text)'::regprocedure) like '%coupon-identity:%', 'checkout_must_lock_coupon_identity_and_products');
select dblink_exec('checkout_coupon_lock', 'rollback'); select dblink_disconnect('checkout_coupon_lock');
select '026_discount_settlement_proof_passed' as result;
