begin;
alter table public.orders add column pricing_source text, add column promotion_ids uuid[] not null default '{}', add column coupon_id uuid references public.coupon_definitions(id) on delete restrict, add column coupon_version_id uuid references public.coupon_versions(id) on delete restrict, add column coupon_discount_bps integer, add column coupon_fixed_discount_cents bigint, add column coupon_starts_at timestamptz, add column coupon_ends_at timestamptz, add column coupon_discount_cents bigint, add column merchandise_original_cents bigint, add column merchandise_discount_cents bigint, add column merchandise_final_cents bigint, add column shipping_cents bigint, add column total_cents bigint, add column payment_amount_cents bigint, add column pricing_snapshot_at timestamptz, add column identity_key_version text, add column coupon_reservation_state text;
alter table public.order_items add column original_cents bigint, add column discount_cents bigint, add column final_cents bigint, add column pricing_source text, add column promotion_id uuid references public.promotion_campaigns(id) on delete restrict, add column promotion_version_id uuid references public.promotion_versions(id) on delete restrict, add column discount_bps integer, add column fixed_discount_cents bigint, add column coupon_id uuid references public.coupon_definitions(id) on delete restrict, add column coupon_version_id uuid references public.coupon_versions(id) on delete restrict;
alter table public.orders add constraint orders_discount_snapshot_check check (integrity_version = 0 or (pricing_source in ('promotions', 'coupon') and merchandise_original_cents >= 0 and merchandise_discount_cents between 0 and merchandise_original_cents and merchandise_final_cents = merchandise_original_cents - merchandise_discount_cents and shipping_cents >= 0 and total_cents = merchandise_final_cents + shipping_cents and payment_amount_cents = total_cents and pricing_snapshot_at is not null and ((pricing_source = 'promotions' and coupon_id is null and coupon_reservation_state = 'none') or (pricing_source = 'coupon' and coupon_id is not null and coupon_version_id is not null and coupon_discount_cents = merchandise_discount_cents and identity_key_version is not null and coupon_reservation_state = 'reserved'))));
alter table public.order_items add constraint order_items_discount_snapshot_check check (integrity_version = 0 or (original_cents >= 0 and discount_cents between 0 and original_cents and final_cents = original_cents - discount_cents and pricing_source in ('promotions', 'coupon') and ((pricing_source = 'promotions' and coupon_id is null and coupon_version_id is null) or (pricing_source = 'coupon' and coupon_id is not null and coupon_version_id is not null))));
create table public.coupon_checkout_reservations (order_id uuid primary key references public.orders(id) on delete restrict, coupon_id uuid not null references public.coupon_definitions(id) on delete restrict, coupon_version_id uuid not null references public.coupon_versions(id) on delete restrict, key_version text not null check (key_version ~ '^[A-Za-z0-9._-]{1,32}$'), fingerprint text not null check (fingerprint ~ '^[0-9a-f]{64}$'), reservation_state text not null default 'reserved' check (reservation_state in ('reserved', 'consumed', 'released', 'expired')), reserved_at timestamptz not null default now(), unique (coupon_id, key_version, fingerprint));
alter table public.coupon_checkout_reservations enable row level security;
revoke all on public.coupon_checkout_reservations from public, anon, authenticated;
create or replace function public.guard_coupon_definition_update() returns trigger language plpgsql set search_path = '' as $function$
begin
  if new.code <> old.code or new.capacity <> old.capacity or new.starts_at <> old.starts_at or new.ends_at <> old.ends_at or new.created_at <> old.created_at then raise exception using errcode = 'P0001', message = 'coupon_terms_immutable'; end if;
  if not old.is_active and new.is_active then raise exception using errcode = 'P0001', message = 'coupon_reactivation_forbidden'; end if;
  if old.is_active and new.is_active then
    if new.deactivated_at is not null or new.deactivation_reason is not null then raise exception using errcode = 'P0001', message = 'coupon_deactivation_fields_invalid'; end if;
    if new.used_count <> old.used_count and new.used_count <> old.used_count + 1 then raise exception using errcode = 'P0001', message = 'coupon_used_count_immutable'; end if;
    return new;
  end if;
  if new.used_count <> old.used_count then raise exception using errcode = 'P0001', message = 'coupon_used_count_immutable'; end if;
  if old.is_active and (new.deactivated_at is null or btrim(coalesce(new.deactivation_reason, '')) = '') then raise exception using errcode = 'P0001', message = 'coupon_deactivation_reason_required'; end if;
  if not old.is_active and (new.deactivated_at, new.deactivation_reason) is distinct from (old.deactivated_at, old.deactivation_reason) then raise exception using errcode = 'P0001', message = 'coupon_deactivation_immutable'; end if;
  return new;
end;
$function$;

create or replace function public.prevent_order_checkout_authority_mutation() returns trigger language plpgsql set search_path = '' as $function$
begin if old.integrity_version = 1 and (new.user_id, new.purchase_user_id, new.total_amount, new.shipping_fee, new.shipping_info, new.payment_amount, new.payment_currency, new.payment_reference, new.payment_expires_at, new.pricing_source, new.promotion_ids, new.coupon_id, new.coupon_version_id, new.coupon_discount_bps, new.coupon_fixed_discount_cents, new.coupon_starts_at, new.coupon_ends_at, new.coupon_discount_cents, new.merchandise_original_cents, new.merchandise_discount_cents, new.merchandise_final_cents, new.shipping_cents, new.total_cents, new.payment_amount_cents, new.pricing_snapshot_at, new.identity_key_version, new.coupon_reservation_state) is distinct from (old.user_id, old.purchase_user_id, old.total_amount, old.shipping_fee, old.shipping_info, old.payment_amount, old.payment_currency, old.payment_reference, old.payment_expires_at, old.pricing_source, old.promotion_ids, old.coupon_id, old.coupon_version_id, old.coupon_discount_bps, old.coupon_fixed_discount_cents, old.coupon_starts_at, old.coupon_ends_at, old.coupon_discount_cents, old.merchandise_original_cents, old.merchandise_discount_cents, old.merchandise_final_cents, old.shipping_cents, old.total_cents, old.payment_amount_cents, old.pricing_snapshot_at, old.identity_key_version, old.coupon_reservation_state) then raise exception using errcode = 'P0001', message = 'immutable_product_checkout_authority'; end if; return new; end;
$function$;
create or replace function public.prevent_order_item_checkout_authority_mutation() returns trigger language plpgsql set search_path = '' as $function$
begin if old.integrity_version = 1 and (new.order_id, new.product_id, new.price, new.product_title_snapshot, new.original_cents, new.discount_cents, new.final_cents, new.pricing_source, new.promotion_id, new.promotion_version_id, new.discount_bps, new.fixed_discount_cents, new.coupon_id, new.coupon_version_id) is distinct from (old.order_id, old.product_id, old.price, old.product_title_snapshot, old.original_cents, old.discount_cents, old.final_cents, old.pricing_source, old.promotion_id, old.promotion_version_id, old.discount_bps, old.fixed_discount_cents, old.coupon_id, old.coupon_version_id) then raise exception using errcode = 'P0001', message = 'immutable_product_order_item_authority'; end if; return new; end;
$function$;

create function public.create_product_checkout(p_user_id text, p_shipping_info jsonb, p_product_ids uuid[], p_shipping_fee numeric, p_pricing_source text, p_coupon_code text, p_identity_key_version text, p_identity_fingerprint text)
returns table(order_id uuid, reference text, expires_at timestamptz, preference_items jsonb) language plpgsql security definer set search_path = '' as $function$
declare v_order public.orders%rowtype; v_coupon record; v_product record; v_count integer := 0; v_merchandise bigint := 0; v_discount bigint := 0; v_shipping bigint := round(p_shipping_fee * 100)::bigint; v_total bigint; v_promotion_ids uuid[] := '{}'; v_source text := coalesce(p_pricing_source, 'promotions'); v_code text := upper(btrim(coalesce(p_coupon_code, ''))); v_reference text := 'order:' || gen_random_uuid()::text;
begin
  select null::uuid id, null::uuid version_id, null::public.coupon_discount_kind discount_kind, null::integer discount_bps, null::bigint fixed_discount_cents, null::timestamptz starts_at, null::timestamptz ends_at into v_coupon;
  if p_user_id is null or btrim(p_user_id) = '' or p_shipping_info is null or jsonb_typeof(p_shipping_info) <> 'object' or nullif(btrim(p_shipping_info ->> 'email'), '') is null or nullif(btrim(p_shipping_info ->> 'fullName'), '') is null or p_shipping_fee is null or v_shipping < 0 or coalesce(cardinality(p_product_ids), 0) = 0 or array_position(p_product_ids, null) is not null or cardinality(p_product_ids) <> (select count(distinct id) from unnest(p_product_ids) id) or v_source not in ('promotions', 'coupon') or (v_source = 'promotions' and (p_coupon_code is not null or p_identity_key_version is not null or p_identity_fingerprint is not null)) or (v_source = 'coupon' and (v_code !~ '^[A-Z0-9-]{3,64}$' or coalesce(p_identity_key_version, '') !~ '^[A-Za-z0-9._-]{1,32}$' or coalesce(p_identity_fingerprint, '') !~ '^[0-9a-f]{64}$')) then raise exception using errcode = '22023', message = 'invalid_product_checkout'; end if;
  perform 1 from public.profiles where id = p_user_id for key share; if not found then raise exception using errcode = 'P0001', message = 'user_profile_not_found'; end if;
  if v_source = 'coupon' then
    perform pg_advisory_xact_lock(hashtextextended('coupon-code:' || v_code, 0)); select definitions.*, versions.id version_id, versions.discount_kind, versions.discount_bps, versions.fixed_discount_cents into v_coupon from public.coupon_definitions definitions join public.coupon_versions versions on versions.coupon_id = definitions.id and versions.version_number = 1 where definitions.code = v_code for update of definitions;
    if not found or not v_coupon.is_active or v_coupon.starts_at > statement_timestamp() or v_coupon.ends_at <= statement_timestamp() or v_coupon.used_count >= v_coupon.capacity then raise exception using errcode = 'P0001', message = 'coupon_unavailable'; end if;
    perform pg_advisory_xact_lock(hashtextextended('coupon-identity:' || v_coupon.id::text || ':' || p_identity_key_version || ':' || p_identity_fingerprint, 0)); if exists (select 1 from public.coupon_checkout_reservations where coupon_id = v_coupon.id and key_version = p_identity_key_version and fingerprint = p_identity_fingerprint) or exists (select 1 from public.coupon_identity_uses where coupon_id = v_coupon.id and key_version = p_identity_key_version and fingerprint = p_identity_fingerprint) then raise exception using errcode = 'P0001', message = 'coupon_identity_already_used'; end if;
  end if;
  for v_product in select id, title, round(price * 100)::bigint cents from public.products where id = any(p_product_ids) order by id for update loop if (select status from public.products where id = v_product.id) <> 'available'::public.product_status then raise exception using errcode = 'P0001', message = 'product_not_available'; end if; v_count := v_count + 1; v_merchandise := v_merchandise + v_product.cents; end loop;
  if v_count <> cardinality(p_product_ids) then raise exception using errcode = 'P0001', message = 'product_not_found'; end if;
  if v_merchandise <= 0 then raise exception using errcode = '22023', message = 'invalid_product_checkout'; end if;
  if v_source = 'coupon' then v_discount := case when v_coupon.discount_kind = 'percentage' then v_merchandise * v_coupon.discount_bps / 10000 else least(v_coupon.fixed_discount_cents, v_merchandise / 2) end; else select coalesce(sum(round(products.price * 100)::bigint * coalesce((select versions.discount_bps from public.promotion_campaigns campaigns join public.promotion_versions versions on versions.promotion_id = campaigns.id and versions.version_number = 1 join public.promotion_targets targets on targets.promotion_id = campaigns.id where campaigns.is_active and campaigns.starts_at <= statement_timestamp() and campaigns.ends_at > statement_timestamp() and targets.product_type_id = products.product_type_id and (targets.product_subtype_id is null or targets.product_subtype_id = products.product_subtype_id) order by campaigns.ends_at, campaigns.id limit 1), 0) / 10000), 0) into v_discount from public.products products where products.id = any(p_product_ids); end if;
  if v_source = 'promotions' then select coalesce(array_agg(distinct choice.promotion_id) filter (where choice.promotion_id is not null), '{}') into v_promotion_ids from (select (select campaigns.id from public.promotion_campaigns campaigns join public.promotion_targets targets on targets.promotion_id = campaigns.id where campaigns.is_active and campaigns.starts_at <= statement_timestamp() and campaigns.ends_at > statement_timestamp() and targets.product_type_id = products.product_type_id and (targets.product_subtype_id is null or targets.product_subtype_id = products.product_subtype_id) order by campaigns.ends_at, campaigns.id limit 1) promotion_id from public.products products where products.id = any(p_product_ids)) choice; end if;
  v_total := v_merchandise - v_discount + v_shipping;
  insert into public.orders (user_id, customer_email, customer_name, status, total_amount, shipping_fee, shipping_info, integrity_version, purchase_user_id, payment_amount, payment_currency, payment_reference, payment_expires_at, pricing_source, promotion_ids, coupon_id, coupon_version_id, coupon_discount_bps, coupon_fixed_discount_cents, coupon_starts_at, coupon_ends_at, coupon_discount_cents, merchandise_original_cents, merchandise_discount_cents, merchandise_final_cents, shipping_cents, total_cents, payment_amount_cents, pricing_snapshot_at, identity_key_version, coupon_reservation_state) values (p_user_id, p_shipping_info ->> 'email', p_shipping_info ->> 'fullName', 'pending', v_total / 100.0, v_shipping / 100.0, p_shipping_info, 1, p_user_id, v_total / 100.0, 'ARS', v_reference, now() + make_interval(mins => 15), v_source, v_promotion_ids, case when v_source = 'coupon' then v_coupon.id end, case when v_source = 'coupon' then v_coupon.version_id end, case when v_source = 'coupon' then v_coupon.discount_bps end, case when v_source = 'coupon' then v_coupon.fixed_discount_cents end, case when v_source = 'coupon' then v_coupon.starts_at end, case when v_source = 'coupon' then v_coupon.ends_at end, case when v_source = 'coupon' then v_discount end, v_merchandise, v_discount, v_merchandise - v_discount, v_shipping, v_total, v_total, statement_timestamp(), case when v_source = 'coupon' then p_identity_key_version end, case when v_source = 'coupon' then 'reserved' else 'none' end) returning * into v_order;
  insert into public.order_items (order_id, product_id, price, integrity_version, product_title_snapshot, original_cents, discount_cents, final_cents, pricing_source, promotion_id, promotion_version_id, discount_bps, fixed_discount_cents, coupon_id, coupon_version_id)
  with priced as (select products.id, products.title, round(products.price * 100)::bigint original_cents, promotions.id promotion_id, promotions.version_id, promotions.discount_bps from public.products products left join lateral (select campaigns.id, versions.id version_id, versions.discount_bps from public.promotion_campaigns campaigns join public.promotion_versions versions on versions.promotion_id = campaigns.id and versions.version_number = 1 join public.promotion_targets targets on targets.promotion_id = campaigns.id where campaigns.is_active and campaigns.starts_at <= statement_timestamp() and campaigns.ends_at > statement_timestamp() and targets.product_type_id = products.product_type_id and (targets.product_subtype_id is null or targets.product_subtype_id = products.product_subtype_id) order by campaigns.ends_at, campaigns.id limit 1) promotions on v_source = 'promotions' where products.id = any(p_product_ids)), allocated as (select *, case when v_source = 'promotions' then original_cents * coalesce(discount_bps, 0) / 10000 else (v_discount * original_cents / v_merchandise) + case when row_number() over (order by (v_discount * original_cents % v_merchandise) desc, id) <= v_discount - sum(v_discount * original_cents / v_merchandise) over () then 1 else 0 end end discount_cents from priced) select v_order.id, id, (original_cents - discount_cents) / 100.0, 1, title, original_cents, discount_cents, original_cents - discount_cents, v_source, promotion_id, version_id, case when v_source = 'promotions' then discount_bps else v_coupon.discount_bps end, case when v_source = 'coupon' then v_coupon.fixed_discount_cents end, case when v_source = 'coupon' then v_coupon.id end, case when v_source = 'coupon' then v_coupon.version_id end from allocated;
  for v_product in select id from public.products where id = any(p_product_ids) order by id loop insert into public.inventory_reservations (order_id, product_id, expires_at) values (v_order.id, v_product.id, v_order.payment_expires_at); update public.products set status = 'reserved', reserved_at = now() where id = v_product.id and status = 'available'::public.product_status; if not found then raise exception using errcode = 'P0001', message = 'product_reservation_conflict'; end if; end loop;
  if v_source = 'coupon' then update public.coupon_definitions set used_count = used_count + 1 where id = v_coupon.id and used_count < capacity; if not found then raise exception using errcode = 'P0001', message = 'coupon_capacity_conflict'; end if; insert into public.coupon_checkout_reservations (order_id, coupon_id, coupon_version_id, key_version, fingerprint) values (v_order.id, v_coupon.id, v_coupon.version_id, p_identity_key_version, p_identity_fingerprint); end if;
  order_id := v_order.id; reference := v_order.payment_reference; expires_at := v_order.payment_expires_at; select jsonb_agg(jsonb_build_object('id', items.product_id, 'title', items.product_title_snapshot, 'price', items.price) order by items.product_id) into preference_items from public.order_items items where items.order_id = v_order.id; return next;
end;
$function$;
create or replace function public.create_product_checkout(p_user_id text, p_shipping_info jsonb, p_product_ids uuid[], p_shipping_fee numeric) returns table(order_id uuid, reference text, expires_at timestamptz, preference_items jsonb) language sql security definer set search_path = '' as $function$ select * from public.create_product_checkout(p_user_id, p_shipping_info, p_product_ids, p_shipping_fee, 'promotions', null, null, null); $function$;
revoke execute on function public.create_product_checkout(text,jsonb,uuid[],numeric,text,text,text,text) from public, anon, authenticated;
grant execute on function public.create_product_checkout(text,jsonb,uuid[],numeric,text,text,text,text) to service_role, postgres;
commit;
