insert into public.product_types (name) values
  ('Remeras y tops'),
  ('Camisas y blusas'),
  ('Buzos y tejidos'),
  ('Abrigos'),
  ('Pantalones'),
  ('Shorts y polleras'),
  ('Vestidos y enteritos'),
  ('Conjuntos'),
  ('Calzado'),
  ('Accesorios')
on conflict (lower(name)) do nothing;

insert into public.product_subtypes (product_type_id, name)
select product_types.id, seed.name
from (
  values
    ('Remeras y tops', 'Remeras'),
    ('Remeras y tops', 'Musculosas'),
    ('Remeras y tops', 'Tops'),
    ('Remeras y tops', 'Polos'),
    ('Remeras y tops', 'Manga larga'),
    ('Camisas y blusas', 'Camisas'),
    ('Camisas y blusas', 'Blusas'),
    ('Camisas y blusas', 'Sobrecamisas'),
    ('Camisas y blusas', 'Camisas de manga corta'),
    ('Buzos y tejidos', 'Hoodies'),
    ('Buzos y tejidos', 'Buzos'),
    ('Buzos y tejidos', 'Sweaters'),
    ('Buzos y tejidos', 'Cardigans'),
    ('Buzos y tejidos', 'Poleras'),
    ('Abrigos', 'Camperas'),
    ('Abrigos', 'Chaquetas'),
    ('Abrigos', 'Blazers'),
    ('Abrigos', 'Tapados'),
    ('Abrigos', 'Trenchs y pilotos'),
    ('Abrigos', 'Chalecos'),
    ('Pantalones', 'Jeans'),
    ('Pantalones', 'Pantalones cargo'),
    ('Pantalones', 'Pantalones de vestir'),
    ('Pantalones', 'Joggers'),
    ('Pantalones', 'Leggings'),
    ('Shorts y polleras', 'Shorts'),
    ('Shorts y polleras', 'Bermudas'),
    ('Shorts y polleras', 'Polleras'),
    ('Shorts y polleras', 'Minifaldas'),
    ('Shorts y polleras', 'Skorts'),
    ('Vestidos y enteritos', 'Vestidos cortos'),
    ('Vestidos y enteritos', 'Vestidos largos'),
    ('Vestidos y enteritos', 'Monos'),
    ('Vestidos y enteritos', 'Jardineros'),
    ('Conjuntos', 'Conjuntos deportivos'),
    ('Conjuntos', 'Conjuntos tejidos'),
    ('Conjuntos', 'Trajes'),
    ('Conjuntos', 'Sets de dos piezas'),
    ('Calzado', 'Zapatillas'),
    ('Calzado', 'Botas y borcegos'),
    ('Calzado', 'Zapatos'),
    ('Calzado', 'Mocasines'),
    ('Calzado', 'Sandalias'),
    ('Accesorios', 'Gorras y sombreros'),
    ('Accesorios', 'Carteras y bolsos'),
    ('Accesorios', 'Mochilas'),
    ('Accesorios', 'Cinturones'),
    ('Accesorios', 'Pañuelos y bufandas'),
    ('Accesorios', 'Anteojos'),
    ('Accesorios', 'Joyería'),
    ('Accesorios', 'Medias')
) as seed(product_type_name, name)
join public.product_types on lower(product_types.name) = lower(seed.product_type_name)
on conflict (product_type_id, lower(name)) do nothing;
